### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mimorisuzuko** [mimorisuzuko/himawari#1]
- [ ] Step 0: Electron (WR) <-> Server
- [ ] Step 1: Electron (WR) <-> Server <-> Browser (R)
- [ ] Step 2: Electron (WR) <-> Server <-> Browser (WR)
